### ISSUE TITLE
error after fresh install

### ISSUE THREAD

**Issue by NugzarGaguliya** [codebandits/react-app-rewire-css-modules#12]
After install, I'm getting this error 

```
C:\projects\react-architecture\node_modules\react-app-rewire-less-modules\index.js:28
            ...cssRules.use,
                        ^

TypeError: Cannot read property 'use' of undefined
    at createRule (C:\projects\react-architecture\node_modules\react-app-rewire-less-modules\index.js:28:25)
    at C:\projects\react-architecture\node_modules\react-app-rewire-less-modules\index.js:47:29
    at Object.override [as webpack] (C:\projects\react-architecture\config-overrides.js:7:12)
    at Object.<anonymous> (C:\projects\react-architecture\node_modules\react-app-rewired\scripts\start.js:13:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

```javascript
  "devDependencies": {
    "react-app-rewire-less-modules": "^1.3.0",
    "react-app-rewired": "1.5.2",
    "react-scripts": "1.1.4"
  }
```

```javascript
const rewireLess = require('react-app-rewire-less-modules');

module.exports = function override(config, env) {

  config = rewireLess(config, env);

  return config;
};
```

**Comment by lnhrdt** [comment]
Closing this issue and archiving this project in favor of Create React App's [native support for CSS Modules](https://facebook.github.io/create-react-app/docs/adding-a-css-modules-stylesheet) introduced in v2.
